### ISSUE TITLE
Running examples fail

### ISSUE THREAD

**Issue by vogella** [2d-inc/Flare-Flutter#184]
If I try to run the examples from their repo, I receive the following error:
````
vogella@vogella-ThinkPad-T570:~/git/Flare-Flutter/example/slider$ flutter run
Because every version of flare_flutter from path depends on flare_dart from hosted and slider depends on flare_dart from path, flare_flutter from path is forbidden.
So, because slider depends on flare_flutter from path, version solving failed.
Running "flutter pub get" in slider...                                  
pub get failed (1)
````

**Comment by umberto-sonnino** [comment]
Thanks for the report, we're looking into it! 
If you want to run the example in the meantime just remove the `flare_dart` dependency from `pubspec.yaml` in `examples/slider`:
```
[...]
dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ../../flare_flutter
  cupertino_icons: ^0.1.2
[...]
```
