### ISSUE TITLE
Error: The method 'hashValues' isn't defined for the class 'AssetFlare'

### ISSUE THREAD

**Issue by finau** [2d-inc/Flare-Flutter#325]
I can't able to build my App, the following error show up.  It's more like [this error](https://github.com/letsar/flutter_slidable/issues/511) on different library.

```
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/flare_flutter-3.0.2/lib/provider/asset_flare.dart:25:23: Error: The method
'hashValues' isn't defined for the class 'AssetFlare'.
```

Any solution or advice on how to fix this issue?

Flutter (Channel stable, 3.27.0, on macOS 14.5 23F79 darwin-x64

**Comment by cmkramer** [comment]
Same problem here:

Flutter (Channel stable, 3.27.0, on macOS 15.2 24C101 darwin-arm64, locale en-US)
Xcode - develop for iOS and macOS (Xcode 16.2)

**Comment by mbfakourii** [comment]
Until the PR is checked, you can use the following git import

```yaml
flare_flutter:
  git:
    url: https://github.com/mbfakourii/Flare-Flutter.git
    ref: remove_hashValues
```

**Comment by mbfakourii** [comment]
Until the [PR](https://github.com/2d-inc/Flare-Flutter/pull/327) is checked, you can use the following git import

```yaml
flare_flutter:
  git:
    url: https://github.com/mbfakourii/Flare-Flutter.git
    path: flare_flutter
    ref: remove_hashValues
```
